### ISSUE TITLE
.history

### ISSUE THREAD

**Issue by gibkigonzo** [norbertkrzeminski/learning#1]
Folder `.history` wygląda na jakiś syf :thinking: To są jakieś logi?
Generalnie do gita nie powinno się wrzucać logów albo zewnętrznych paczek które są zależnościami projektu (folder node_modules). Z tego względu że często są duże i nie wnoszą żadnych sensownych informacji co się rzeczywiście zmieniło.
Żeby powiedzieć git'owi "nie śledź zmian tych plików" to trzeba stworzyć plik `.gitignore` i tam wrzucić nazwe pliku/folderu którego git nie ma śledzić.
```
.history
```
W tym wypadku ten folder już jest śledzony przez git'a więc jak go dodasz do .gitignore i usuniesz to on tej zmiany nie wychwyci i pliki będą dalej w repo. Więc po dodaniu folderu do .gitignore trzeba usunąć folder za pomocą git'a `git rm -r --cached .history`. W tym momencie folder/plik będzie usunięty z repo i nie będzie już śledzony.
Noo ale nie wiem czy to jest syf :hankey: Jednak może się przyda info na przyszłość ;)

**Comment by gibkigonzo** [comment]
podobna sytuacja z `.DS_Store` :thinking:

**Comment by norbertkrzeminski** [comment]
Dzięki za info :)

issue fixed
