### ISSUE TITLE
trochę uwag do styli

### ISSUE THREAD

**Issue by gibkigonzo** [norbertkrzeminski/learning#2]
```
span {
    display: inline-block;
    padding: 20px;
    margin: 20px;
}

div {
    /* display: inline; */
    border: 2px solid crimson;
    margin: 20px;
    padding: 20px;
}
div p {
    border: inherit;
    margin: inherit;
    padding: inherit;
}
a[href*="google"] {
    background-color: rgb(96, 190, 96);
    color: white;
    text-decoration: none;
    font-weight: bold;
    text-transform: uppercase;
}
```
Nie styluj po tagach. Zamiast tego dodaj klasę do taga i styluj po klasie. div'ów na stronie będzie mnóstwo, do tego nie wiadomo czym jest ten div na stronie itp.
poczytaj o BEM http://getbem.com/introduction/

Nadawanie klas pozwala Ci łapać bezpośrednio element.
```
<div>
  <div>
    <p>test</p>
  </div>
    <p>test2</p>
  <div>
    <p>test</p>
  </div>
</div>
```
Jak nadać paragrafowi z text kolor czerwony za pomocą tagów jednocześnie nie zmieniając koloru paragrafu z text2?
```
div div p {
  color: #f00;
}
```
Niby ok, ale co jak dojdzie coś takiego:
```
<div>
  <div>
    <p>test</p>
  </div>
    <p>test</p>
  <div>
    <p>test</p>
  </div>
  <div>
    <div>
      <p>nie chce być czerwony</p>
    </div>
  </div>
</div>
```

Tutaj zaczynają się schody i prawdziwa rzeźba. Chyba że użyjesz klas wtedy możesz nadać im nazwy które mają jakiś sens. BEM to dobry początek :)

Używaj tylko jeden sposób zapisywania kolorów. To zwiększa czytelność i spójność kodu. 
```
    background-color: rgb(96, 190, 96);
    color: white;
```
Do tego nie używaj nazw kolorów, tylko wartości. W przypadku `white` to zawsze będzie biały ale `border: 2px solid crimson;`, co to jest crimson? Na design'ie nie będzie koloru crimson bo nie wiadomo jak tą nazwe poszczególna przeglądarka interpretuje, tzn jaką wartość przypisuje temu wyrazowi.
Przeważnie programy graficzne podają wartości w hexach, czyli biały `#ffffff` albo rgb `rgb(255,255,255)`. Można łatwo znaleźć stronę na której są przeliczane hexy na rgb i na odwrót. Plusem rgb jest to że można użyć `rgba` gdzie jako czwarty parametr podajemy współczynnik alpha czy przeźroczystość `rgba(0, 0, 0, 0.5)`. W przypadku hexa trzeba się posiłkować opacity.

**Comment by gibkigonzo** [comment]
zresztą widzę że rzeźba już się zaczynała :D
```
div {
    /* display: inline; */
    border: 2px solid crimson;
    margin: 20px;
    padding: 20px;
}
div p {
    border: inherit;
    margin: inherit;
    padding: inherit;
}
```
pierwsze style diva zostały przekazane niżej na paragraf, więc później musiałeś wyłączać style na paragrafie. Do tego musiałeś zwiększyć specyfikacje i użyć dwóch tagów. To też jest kolejny argument za tym żeby używać klas. Później musiałbyś używać trzech tagów albo bawić się kolejnością zdefiniowanych styli itd. To ciebie zaprowadzi tylko w jedno miejsce
https://media0.giphy.com/media/ToMjGpzot8uTh5nUwnu/200.gif

**Comment by gibkigonzo** [comment]
Jak w tutorialu napisali że można stylować po tagach to powinni od razu dodać że nie powinno się tego robić. To powinno być zabronione, tak samo jak używanie `!important`. Stylowanie po tagach przydaje się przy tak zwanych resetach. Każda przeglądarka nadaje tagom swoje style, co może powodować że na każdej przeglądarce twoje style bedą wyglądały inaczej. Więc nadaje się wszystkim używanym tagom jednakowe style za pomocą reset'a. Dzięki temu jesteśmy pewni tego od czego zaczynamy i że wszędzie będzie to samo. https://meyerweb.com/eric/tools/css/reset/

**Comment by norbertkrzeminski** [comment]
Cześć,
Refactorowałem część kodu z marioprojekt https://github.com/norbertkrzeminski/learning/tree/marioproject_BEM/2ndcourse/mario_projekt. 

Things to do:
- zaimplementować BEM do Media queries

**Comment by gibkigonzo** [comment]
siema, widziałem prkę, zajebiście wygląda :) :+1: To zamykam issue ;P
